"""table dodoproduct

Revision ID: 2eeb009f3ae7
Revises: 
Create Date: 2025-03-30 21:32:28.012483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eeb009f3ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dodo_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('size', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('city_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dodo_products')
    # ### end Alembic commands ###
